<?php
require('fpdf.php');

class PDF extends FPDF
{
    function ChapterBody($file)
{
    // Read text file
    $txt = file_get_contents($file);
    // Times 12
    $this->SetFont('Times','',12);
    // Output justified text
    $this->MultiCell(0,5,$txt);
    // Line break
    $this->Ln();
    // Mention in italics
    $this->SetFont('','I');
    $this->Cell(0,5,'(end of excerpt)');
}

function PrintChapter($num, $title, $file)
{
    $this->AddPage();
    $this->ChapterTitle($num,$title);
    $this->ChapterBody($file);
}
}

$logoFile = "img/logo.png";
$logoXPos = 10;
$logoYPos = 10;
$logoWidth = 50;
$firstname = $_POST['firstname'];
$lastname = $_POST['lastname'];
$mi = $_POST['mi'];
$date = $_POST['date'];
$streetaddress = $_POST['streetaddress'];
$aptnum = $_POST['aptnum'];
$city = $_POST['city'];
$state = $_POST['state'];
$zip = $_POST['zip'];
$phone = $_POST['phone'];
$email = $_POST['email'];
$dateavailable = $_POST['dateavailable'];
$socnumber = $_POST['socnumber'];
$desiredsalary = $_POST['desiredsalary'];
$position = $_POST['position'];
$uscitizenyes = $_POST['uscitizenyes'];
$uscitizenno = $_POST['uscitizenno'];
$authorizedyes = $_POST['authorizedyes'];
$authorizedno = $_POST['authorizedno'];
$prevemployeeyes = $_POST['prevemployeeyes'];
$prevemployeeno = $_POST['prevemployeeno'];
$whenprev = $_POST['whenprev'];
$felonyyes = $_POST['felonyyes'];
$felonyno = $_POST['felonyno'];
$explainfel = $_POST['explainfel'];
$hs = $_POST['hs'];
$hsaddress = $_POST['hsaddress'];
$hsfrom = $_POST['hsfrom'];
$hsto = $_POST['hsto'];
$hsgradyes = $_POST['hsgradyes'];
$hsgradno = $_POST['hsgradno'];
$diploma = $_POST['diploma'];
$college = $_POST['college'];
$collegeaddress = $_POST['collegeaddress'];
$collegefrom = $_POST['collegefrom'];
$collegeto = $_POST['collegeto'];
$collgradyes = $_POST['collgradyes'];
$collgradno = $_POST['collgradno'];
$degree = $_POST['degree'];
$other = $_POST['other'];
$otheraddress = $_POST['otheraddress'];
$otherfrom = $_POST['otherfrom'];
$otherto = $_POST['otherto'];
$othgradyes = $_POST['othgradyes'];
$othgradno = $_POST['othgradno'];
$otherdegree = $_POST['otherdegree'];
$refname = $_POST['refname'];
$refrelationship = $_POST['refrelationship'];
$refcompany = $_POST['refcompany'];
$refphone = $_POST['refphone'];
$refaddress = $_POST['refaddress'];
$refnametwo = $_POST['refnametwo'];
$refrelationshiptwo = $_POST['refrelationshiptwo'];
$refcompanytwo = $_POST['refcompanytwo'];
$refphonetwo = $_POST['refphonetwo'];
$refaddresstwo = $_POST['refaddresstwo'];
$refnamethree = $_POST['refnamethree'];
$refrelationshipthree = $_POST['refrelationshipthree'];
$refcompanythree = $_POST['refcompanythree'];
$refphonethree = $_POST['refphonethree'];
$refaddressthree = $_POST['refaddressthree'];
$prevcompany = $_POST['prevcompany'];
$prevcompphone = $_POST['prevcompphone'];
$prevcompaddress = $_POST['prevcompaddress'];
$supervisor = $_POST['supervisor'];
$jobtitle = $_POST['jobtitle'];
$startingsalary = $_POST['startingsalary'];
$endingsalary = $_POST['endingsalary'];
$responsibilities = $_POST['responsibilities'];
$jobfrom = $_POST['jobfrom'];
$jobto = $_POST['jobto'];
$reasonforleaving = $_POST['reasonforleaving'];
$contactemployeryes = $_POST['contactemployeryes'];
$contactemployerno = $_POST['contactemployerno'];
$prevcompanytwo = $_POST['prevcompanytwo'];
$prevcompphonetwo = $_POST['prevcompphonetwo'];
$prevcompaddresstwo = $_POST['prevcompaddresstwo'];
$supervisortwo = $_POST['supervisortwo'];
$jobtitletwo = $_POST['jobtitletwo'];
$startingsalarytwo = $_POST['startingsalarytwo'];
$endingsalarytwo = $_POST['endingsalarytwo'];
$responsibilitiestwo = $_POST['responsibilitiestwo'];
$jobfromtwo = $_POST['jobfromtwo'];
$jobtotwo = $_POST['jobtotwo'];
$reasonforleavingtwo = $_POST['reasonforleavingtwo'];
$contactemployertwoyes = $_POST['contactemployertwoyes'];
$contactemployertwono = $_POST['contactemployertwono'];
$militarybranch = $_POST['militarybranch'];
$militaryfrom = $_POST['militaryfrom'];
$militaryto = $_POST['militaryto'];
$rankdischarge = $_POST['rankdischarge'];
$typedischarge = $_POST['typedischarge'];
$explaindischarge = $_POST['explaindischarge'];
$militarybranch = $_POST['militarybranch'];
$signature = $_POST['signature'];
$sigdate = $_POST['sigdate'];


$pdf = new FPDF();
$pdf->AddPage();
$pdf->Image( $logoFile, $logoXPos, $logoYPos, $logoWidth );
$pdf->SetFont('Helvetica','B',14);
$pdf->Multicell(0,2,"\n\n\n\n\n\n\n\n");
$pdf->SetTextColor(0,61,113);
$pdf->Cell(0,0,"General Labor Application", 0, 1, 'C');
$pdf->Multicell(0,2,"\n\n\n\n\n");
$pdf->SetTextColor(0,0,0);
$pdf->SetFont('Helvetica','B',13);
$pdf->Cell(40,10,"Aplicación para empleo",0,2);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Primer Nombre: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(35,10,"$firstname",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Apellido: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$lastname",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(10,10,"Fecha: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$date",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(26,10,"Calle: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(100,10,"$streetaddress",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(29,10,"Apartamento/Unidad: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(10,10,"$aptnum",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(9,10,"Ciudad: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(50,10,"$city",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(11,10,"Estado: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(50,10,"$state",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(18,10,"Codigo Postal: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(10,10,"$zip",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(13,10,"Numero de Teléfono: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(35,10,"$phone",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(11,10,"Correo Electrono: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(90,10,"$email",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(25,10,"Fecha disponible: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$dateavailable",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(32,10,"Número de seguro: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$socnumber",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(26,10,"Sueldo deseado: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$desiredsalary",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(33,10,"Aplicando por: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(100,10,"$position",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(62,10,"¿Usted es ciudadana Americana? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$uscitizenyes $uscitizenno",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(71,10,"¿Si no, usted esta autorizada para trabajar enlos Estados Unidos? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$authorizedyes $authorizedno",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(65,10,"¿Has trabajado por esta compañía? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$prevemployeeyes $prevemployeeno",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(22,10,"¿Cuándo? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->MultiCell(0,5, "$whenprev\n\n\n", 0, 'J', 0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(67,10,"¿Has hecho un crimen en algún tiempo? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$felonyyes $felonyno",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(24,10,"Explica: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->MultiCell(0,5, "$explainfel\n\n\n", 0, 'J', 0,1);
$pdf->SetFont('Helvetica','B',13);
$pdf->Cell(40,10,"Educación",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(24,10,"Escuela Secundaria: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(50,10,"$hs",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Dirección: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$hsaddress",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(11,10,"Desde: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$hsfrom",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(7,10,"Hasta: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$hsto",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(32,10,"¿Usted graduó? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(10,10,"$hsgradyes $hsgradno",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(16,10,"Diploma: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$diploma",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(15,10,"Colegio: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(50,10,"$college",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Dirección ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$collegeaddress",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(11,10,"Desde: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$collegefrom",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(7,10,"Hasta: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$collegeto",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(32,10,"¿Usted graduó? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(10,10,"$collgradyes $collgradno",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(14,10,"Degree: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$degree",0,1);
$pdf->SetFont('Helvetica','B',13);
$pdf->Cell(40,10,"Referencies",0,2);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"Por favor anote dos referencias profesionales.",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Nombre Completo: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(45,10,"$refname",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(24,10,"Relación: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$refrelationship",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Compañía: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(60,10,"$refcompany",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(13,10,"Numero telefónica: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(35,10,"$refphone",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Dirección: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$refaddress",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Nombre Completo: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(45,10,"$refnametwo",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(24,10,"Relación: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$refrelationshiptwo",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Compañía: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(60,10,"$refcompanytwo",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(13,10,"Numero telefónica: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(35,10,"$refphonetwo",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Dirección: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$refaddresstwo",0,1);
$pdf->SetFont('Helvetica','B',13);
$pdf->Cell(40,10,"Empleo Anterior",0,2);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Compañía: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(60,10,"$prevcompany",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(13,10,"Numero telefónica: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(35,10,"$prevcompphone",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Dirección: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(95,10,"$prevcompaddress",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(21,10,"Supervisor: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$supervisor",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Título de trabajo: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(45,10,"$jobtitle",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(28,10,"Sueldo Empezando ($): ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$startingsalary",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(26,10,"Sueldo Final ($): ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$endingsalary",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(30,10,"Responsabilidades: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->MultiCell(0,5, "$responsibilities\n\n\n", 0, 'J', 0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(11,10,"Desde: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$jobfrom",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(7,10,"Hasta: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$jobto",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(35,10,"Motivo por dejar detrabajar: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->MultiCell(0,5, "$reasonforleaving\n\n\n", 0, 'J', 0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(95,10,"¿Podemos contactar su supervisor anterior? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(10,10,"$contactemployeryes $contactemployerno",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(20,10,"Compañía: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(60,10,"$prevcompanytwo",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(13,10,"Numero telefónica: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(35,10,"$prevcompphonetwo",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Dirección: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(95,10,"$prevcompaddresstwo",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(21,10,"Supervisor: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$supervisortwo",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(17,10,"Título de trabajo: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(45,10,"$jobtitletwo",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(28,10,"Sueldo Empezando ($): ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$startingsalarytwo",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(26,10,"Sueldo Final ($): ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(20,10,"$endingsalarytwo",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(30,10,"Responsabilidades: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->MultiCell(0,5, "$responsibilitiestwo\n\n\n", 0, 'J', 0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(11,10,"Desde: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$jobfromtwo",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(7,10,"Hasta: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$jobtotwo",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(35,10,"Motivo por dejar detrabajar: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->MultiCell(0,5, "$reasonforleavingtwo\n\n\n", 0, 'J', 0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(95,10,"¿Podemos contactar su supervisor anterior? ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(10,10,"$contactemployertwoyes $contactemployertwono",0,1);
$pdf->SetFont('Helvetica','B',13);
$pdf->Cell(40,10,"Servicio Militar",0,2);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(15,10,"Tipo de Servicio: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(65,10,"$militarybranch",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(11,10,"Desde: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$militaryfrom",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(7,10,"Hasta: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(22,10,"$militaryto",0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(33,10,"Posición/Titulo: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$typedischarge",0,1);
$pdf->SetFont('Helvetica','B',13);
$pdf->Cell(40,10,"La renuncia y firma",0,2);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"Certifico que mis respuestas son verdaderas y completas a mi mejor conocimiento.",0,2);
$pdf->MultiCell(0,5, "Si esta aplicación conduce al empleo, entiendo que la información falsa o engañosa en mi solicitud o entrevista puede resultar en mi liberación.", 0, 'J', 0,1);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(19,10,"Firma: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(50,10,"$signature",0,0);
$pdf->SetFont('Helvetica','',10);
$pdf->Cell(10,10,"Fecha: ",0,0);
$pdf->SetFont('Helvetica','B',10);
$pdf->Cell(40,10,"$sigdate",0,2);

$pdf->Output();
?>